
#########################################################################################		
SQL_CREATE_INDEX = alter table EBANK_PLAN_VOUCHER_DESYEAR  add constraint PK_EBANK_PLAN_VOUCHER_DESYEAR primary key (ID, FINANCE_CODE, SET_YEAR)@\
create unique index INDEX_EBANKPLANVOUCHER_DESYEAR on EBANK_PLAN_VOUCHER_DESYEAR (VOUCHER_NO, FINANCE_CODE, SET_YEAR)@\
alter table EBANK_PLAN_AGENT_BILL_DESYEAR  add constraint PK_EBANK_PLAN_AGENT_BILL_DESYEAR primary key (ID, FINANCE_CODE, SET_YEAR)@\
create unique index INDEX_EBANKPLANAGENTBILL_DESYEAR on EBANK_PLAN_AGENT_BILL_DESYEAR (BILL_NO, FINANCE_CODE, SET_YEAR)@\
alter table EBANK_PLAN_AGENTEN_BILL_DESYEAR  add constraint PK_PLAN_AGENTEN_BILL_DESYEAR primary key (ID, FINANCE_CODE, SET_YEAR)@\
create unique index INDEX_PLANAGENTENBILL_DESYEAR on EBANK_PLAN_AGENTEN_BILL_DESYEAR (BILL_NO, FINANCE_CODE, SET_YEAR)@\
alter table EBANK_VOUCHER_RECEIVE_LOG_DESYEAR  add constraint PK_VOUCHER_RECEIVE_LOG_DESYEAR primary key (ID)@\
create index IDX_EBANK_VOUCHER_RECEIVE_DESYEAR on EBANK_VOUCHER_RECEIVE_LOG_DESYEAR (FINANCE_CODE, SET_YEAR, VT_CODE, VOUCHER_NO)@\
create index IDX_VOU_RECEIVE_STATUS_DESYEAR on EBANK_VOUCHER_RECEIVE_LOG_DESYEAR (VOUCHER_STATUS, IS_VALID)@\
create unique index UNI_EBANK_VOUCHER_NO_DESYEAR on EBANK_VOUCHER_RECEIVE_LOG_DESYEAR (FINANCE_CODE, SET_YEAR, VT_CODE, VOUCHER_NO, VOUCHER_FLAG, IS_VALID)@\
create index INDEX_BALANCEELEDETAIL_EC_DESYEAR on EBANK_BALANCE_ELE_DETAIL_DESYEAR (ELE_CODE)@\
create index INDEX_BALANCEELEDETAIL_FC_DESYEAR on EBANK_BALANCE_ELE_DETAIL_DESYEAR (FINANCE_CODE)@\
create index INDEX_BALANCEELEDETAIL_SI_DESYEAR on EBANK_BALANCE_ELE_DETAIL_DESYEAR (SUM_ID)@\
create index INDEX_BALANCELIMITMONTHEN_DESYEAR on EBANK_BALANCE_LIMIT_MONTH_DESYEAR (IS_ENABLED)@\
create index INDEX_BALANCELIMITMONTHFC_DESYEAR on EBANK_BALANCE_LIMIT_MONTH_DESYEAR (FINANCE_CODE)@\
create index INDEX_BALANCELIMITMONTHSM_DESYEAR on EBANK_BALANCE_LIMIT_MONTH_DESYEAR (SET_MONTH)@\
create index INDEX_BALANCELIMITMONTHSY_DESYEAR on EBANK_BALANCE_LIMIT_MONTH_DESYEAR (SET_YEAR)@\
create index INDEX_BALANCELIMIT_FC_DESYEAR on EBANK_BALANCE_LIMIT_DESYEAR (FINANCE_CODE)@\
create index INDEX_BALANCELIMIT_SUM_ID_DESYEAR on EBANK_BALANCE_LIMIT_DESYEAR (SUM_ID)@\
create index INDEX_BALANCELIMIT_SY_DESYEAR on EBANK_BALANCE_LIMIT_DESYEAR (SET_YEAR)@\
alter table EBANK_BALANCE_RECORD_DESYEAR  add constraint PRIMARY_EBR_CHR_ID_DESYEAR primary key (CHR_ID)@\
create index INDEX_BALANCERECORD_FC_DESYEAR on EBANK_BALANCE_RECORD_DESYEAR (FINANCE_CODE)@\
create index INDEX_BALANCERECORD_SI_DESYEAR on EBANK_BALANCE_RECORD_DESYEAR (SUM_ID)@\
create index INDEX_BALANCERECORD_SY_DESYEAR on EBANK_BALANCE_RECORD_DESYEAR (SET_YEAR)@\
create index INDEX_BALANCERECORD_VI_DESYEAR on EBANK_BALANCE_RECORD_DESYEAR (VOUCHER_ID)@\
create index INDEX_EBANK_ASSP_VOUCHER_DESYEAR on EBANK_ASSP_VOUCHER_DESYEAR (FINANCE_CODE, VOUCHER_NO)@\
alter table EBANK_PAY_BILL_DESYEAR add constraint PK_EBANK_VOUCHER_BILL_ID_DESYEAR primary key (ID, SET_YEAR, FINANCE_CODE)@\
create unique index INDX_EBANK_BILL_NO_DESYEAR on EBANK_PAY_BILL_DESYEAR (BILL_NO, FINANCE_CODE)@\
create index INDEX_EBANKPAYVOUCHER_DESYEAR on EBANK_PAY_DETAIL_DESYEAR (CLEAR_BILL_ID)@\
alter table EBANK_CORE_LOG_DESYEAR  add constraint EBANK_CORE_LOG_PRIMARY_DESYEAR primary key (LOG_ID)@\
alter table EBANK_PAY_BATCH_BILL_DESYEAR  add constraint PK_PAY_BATCH_BILL_DESYEAR primary key (ID)@\
create index INDEX_EBANK_DAY_BILL_DESYEAR on EBANK_DAY_BILL_DESYEAR (BILL_NO, SET_YEAR, FINANCE_CODE)@\
create index INDEX_EBANK_ACC_BILL_DESYEAR on EBANK_ACC_BILL_DESYEAR (BILL_NO, SET_YEAR, FINANCE_CODE)@\
alter table EBANK_PAYCARD_BILL_DESYEAR add constraint PK_EBANK_PAYCARD_BILL_DESYEAR primary key (ID)@\
alter table EBANK_PAYCARD_BILL_DETAIL_DESYEAR add constraint PK_PAYCARD_BILL_DETAIL_DESYEAR primary key (ID)@\
alter table EBANK_CLEARMONEY_RECOUNT_DESYEAR  add constraint CLEARMONEY_RECOUNT_PK_DESYEAR primary key (BILL_NO, PB_CODE)@\
create index IDX_EBALANCE_RECEIVE_DESYEAR on EBALANCE_RECEIVE_LOG_DESYEAR (VT_CODE, SET_YEAR, VOUCHER_NO, RG_CODE)@\
alter table EBALANCE_RECEIVE_LOG_DESYEAR  add constraint PK_EBALANCE_RECEIVE_LOG_DESYEAR primary key (ID)@\
create index INDX_EBALANCEBILL_NO_DESYEAR on EBALANCE_RECON_BILL_DESYEAR (VOUCHER_CHECK_NO, FINANCE_CODE)@\
alter table EBALANCE_RECON_BILL_DESYEAR add constraint PK_EBALANCE_BILL_ID_DESYEAR primary key (VOUCHER_CHECK_NO, FINANCE_CODE, VT_CODE)@\
create index INDX_EBALANCEDETAIL_NO_DESYEAR on EBALANCE_RECON_DETAIL_DESYEAR 
