-- ebank_balance_limit_month这张表没有注释
#########################################################################################
SQL_CREATE_COMMENT_EBANK_ACC_BILL = comment on column EBANK_ACC_BILL_DESYEAR.id is '主键'@\
comment on column EBANK_ACC_BILL_DESYEAR.bill_no is '凭证编号'@\
comment on column EBANK_ACC_BILL_DESYEAR.en_code is '预算单位编码'@\
comment on column EBANK_ACC_BILL_DESYEAR.en_name is '预算单位名称'@\
comment on column EBANK_ACC_BILL_DESYEAR.en_code1 is '一级预算单位编码'@\
comment on column EBANK_ACC_BILL_DESYEAR.en_name1 is '一级预算单位名称'@\
comment on column EBANK_ACC_BILL_DESYEAR.pay_account_no is '付款人账号'@\
comment on column EBANK_ACC_BILL_DESYEAR.pay_account_name is '付款人名称'@\
comment on column EBANK_ACC_BILL_DESYEAR.pay_account_bank_name is '原付款人银行'@\
comment on column EBANK_ACC_BILL_DESYEAR.pay_money is '支付金额'@\
comment on column EBANK_ACC_BILL_DESYEAR.pb_code is '代理银行编码'@\
comment on column EBANK_ACC_BILL_DESYEAR.pb_name is '代理银行名称'@\
comment on column EBANK_ACC_BILL_DESYEAR.create_date is '生成日期'@\
comment on column EBANK_ACC_BILL_DESYEAR.is_end is '是否结束'@\
comment on column EBANK_ACC_BILL_DESYEAR.is_valid is '是否有效'@\
comment on column EBANK_ACC_BILL_DESYEAR.confirm_date is '确认日期'@\
comment on column EBANK_ACC_BILL_DESYEAR.confirm_user is '确认用户'@\
comment on column EBANK_ACC_BILL_DESYEAR.set_year is '年度'@\
comment on column EBANK_ACC_BILL_DESYEAR.finance_code is '区划'@\
comment on column EBANK_ACC_BILL_DESYEAR.hold1 is '预算字段1'@\
comment on column EBANK_ACC_BILL_DESYEAR.hold2 is '预算字段2'@\
comment on column EBANK_ACC_BILL_DESYEAR.hold3 is '预算字段3'@\
comment on column EBANK_ACC_BILL_DESYEAR.hold4 is '预算字段4'@\
comment on column EBANK_ACC_BILL_DESYEAR.print_date is '打印日期'@\
comment on column EBANK_ACC_BILL_DESYEAR.print_num is '打印次数'@\
comment on column EBANK_ACC_BILL_DESYEAR.print_user is '打印用户'@\
comment on column EBANK_ACC_BILL_DESYEAR.billtype_code is '单据类型'
SQL_CREATE_COMMENT_EBANK_AGENT_BILL = comment on column EBANK_AGENT_BILL_DESYEAR.tre_no is '国库主体代码'@\
comment on column EBANK_AGENT_BILL_DESYEAR.finance_org_no is '财政机关代码'@\
comment on column EBANK_AGENT_BILL_DESYEAR.pay_dictate_no is '支付交易序号'@\
comment on column EBANK_AGENT_BILL_DESYEAR.pay_msg_no is '支付报文编号'@\
comment on column EBANK_AGENT_BILL_DESYEAR.pay_entrust_date is '交易委托日期'@\
comment on column EBANK_AGENT_BILL_DESYEAR.send_operator is '签章发送操作人员'@\
comment on column EBANK_AGENT_BILL_DESYEAR.register_operator is '登记操作人'@\
comment on column EBANK_AGENT_BILL_DESYEAR.register_date is '登记时间'@\
comment on column EBANK_AGENT_BILL_DESYEAR.input_operator is '补录操作人员'@\
comment on column EBANK_AGENT_BILL_DESYEAR.input_date is '补录时间'@\
comment on column EBANK_AGENT_BILL_DESYEAR.create_operator is '生成人'@\
comment on column EBANK_AGENT_BILL_DESYEAR.vt_code is '凭证类型'@\
comment on column EBANK_AGENT_BILL_DESYEAR.clear_date is '清算日期'@\
comment on column EBANK_AGENT_BILL_DESYEAR.voucher_receive_date is '凭证签收日期'
SQL_CREATE_COMMENT_EBANK_ASSP_VOUCHER = comment on table EBANK_ASSP_VOUCHER_DESYEAR is '电子凭证'@\ 
comment on column EBANK_ASSP_VOUCHER_DESYEAR.id is 'ID'@\
comment on column EBANK_ASSP_VOUCHER_DESYEAR.vt_code is '凭证类型'@\
comment on column EBANK_ASSP_VOUCHER_DESYEAR.voucher_no is '凭证号'@\
comment on column EBANK_ASSP_VOUCHER_DESYEAR.voucher_date is '凭证日期（发送日期或接收日期）'@\
comment on column EBANK_ASSP_VOUCHER_DESYEAR.status is '凭证状态：0未接收 1、已接收  2、接收失败 3、签收成功 4、签收失败 5、已回单 6、被退回'@\
comment on column EBANK_ASSP_VOUCHER_DESYEAR.is_send is '1表示发出去的凭证，0表示接收到的凭证'@\
comment on column EBANK_ASSP_VOUCHER_DESYEAR.is_valid is '是否有效'@\
comment on column EBANK_ASSP_VOUCHER_DESYEAR.last_update_date is '最后修改状态日期'@\
comment on column EBANK_ASSP_VOUCHER_DESYEAR.set_year is '年度'@\
comment on column EBANK_ASSP_VOUCHER_DESYEAR.finance_code is '区划'@\
comment on column EBANK_ASSP_VOUCHER_DESYEAR.remark is '备注：可以是退回原因等'
SQL_CREATE_COMMENT_EBANK_BALANCE_RECORD = comment on column EBANK_BALANCE_RECORD_DESYEAR.sum_id is '扣除额度id'@\
comment on column EBANK_BALANCE_RECORD_DESYEAR.use_money is '金额'@\
comment on column EBANK_BALANCE_RECORD_DESYEAR.account_kind is '额度类型'@\
comment on column EBANK_BALANCE_RECORD_DESYEAR.op_time is '扣额度时间'@\
comment on column EBANK_BALANCE_RECORD_DESYEAR.voucher_id is '凭证id'
SQL_CREATE_COMMENT_EBANK_CLEARMONEY_RECOUNT = comment on column EBANK_CLEARMONEY_RECOUNT_DESYEAR.set_year is '年度'@\
comment on column EBANK_CLEARMONEY_RECOUNT_DESYEAR.finance_code is '财政机构'@\
comment on column EBANK_CLEARMONEY_RECOUNT_DESYEAR.main_id is '主建id'@\
comment on column EBANK_CLEARMONEY_RECOUNT_DESYEAR.bill_no is '划款单号'@\
comment on column EBANK_CLEARMONEY_RECOUNT_DESYEAR.pb_code is '银行编码'@\
comment on column EBANK_CLEARMONEY_RECOUNT_DESYEAR.pb_name is '银行名称'@\
comment on column EBANK_CLEARMONEY_RECOUNT_DESYEAR.mk_code is '资金性质编码'@\
comment on column EBANK_CLEARMONEY_RECOUNT_DESYEAR.mk_name is '资金性质名称'@\
comment on column EBANK_CLEARMONEY_RECOUNT_DESYEAR.agent_account_no is '划款帐户帐号'@\
comment on column EBANK_CLEARMONEY_RECOUNT_DESYEAR.agent_account_name is '划款帐户名称'@\
comment on column EBANK_CLEARMONEY_RECOUNT_DESYEAR.agent_account_bank is '划款帐户银行'@\
comment on column EBANK_CLEARMONEY_RECOUNT_DESYEAR.agent_account_bankcode is '划款帐户银行编码'@\
comment on column EBANK_CLEARMONEY_RECOUNT_DESYEAR.payee_account_no is '收款帐户帐号(垫款户)'@\
comment on column EBANK_CLEARMONEY_RECOUNT_DESYEAR.payee_account_name is '收款帐户名称(垫款户)'@\
comment on column EBANK_CLEARMONEY_RECOUNT_DESYEAR.clear_date is '清算日期'@\
comment on column EBANK_CLEARMONEY_RECOUNT_DESYEAR.total_money is '分解金额'@\
comment on column EBANK_CLEARMONEY_RECOUNT_DESYEAR.total_num is '笔数'@\
comment on column EBANK_CLEARMONEY_RECOUNT_DESYEAR.status is '状态  0新增加 1支付 2支付确认'@\
comment on column EBANK_CLEARMONEY_RECOUNT_DESYEAR.remark is '备注'@\
comment on column EBANK_CLEARMONEY_RECOUNT_DESYEAR.create_date is '创建时间'@\
comment on column EBANK_CLEARMONEY_RECOUNT_DESYEAR.pay_date is '支付时间'@\
comment on column EBANK_CLEARMONEY_RECOUNT_DESYEAR.last_op_user is '最后修改人'@\
comment on column EBANK_CLEARMONEY_RECOUNT_DESYEAR.last_op_date is '最后修改时间'
SQL_CREATE_COMMENT_EBANK_CORE_LOG = comment on column EBANK_CORE_LOG_DESYEAR.log_id is '日志ID'@\
comment on column EBANK_CORE_LOG_DESYEAR.method is '调用方法'@\
comment on column EBANK_CORE_LOG_DESYEAR.op_time is '操作时间'@\
comment on column EBANK_CORE_LOG_DESYEAR.finance_code is '财政机构'@\
comment on column EBANK_CORE_LOG_DESYEAR.data_type is '报文类型'@\
comment on column EBANK_CORE_LOG_DESYEAR.in_params is '输入参数'@\
comment on column EBANK_CORE_LOG_DESYEAR.out_params is '输出参数'@\
comment on column EBANK_CORE_LOG_DESYEAR.voucher_no is '凭证号'@\
comment on column EBANK_CORE_LOG_DESYEAR.user_id is '用户ID'@\
comment on column EBANK_CORE_LOG_DESYEAR.pay_account_no is '付款人账号'@\
comment on column EBANK_CORE_LOG_DESYEAR.pay_account_name is '付款人名字'@\
comment on column EBANK_CORE_LOG_DESYEAR.pay_account_bank is '付款人开户行'@\
comment on column EBANK_CORE_LOG_DESYEAR.payee_account_no is '收款人账号'@\
comment on column EBANK_CORE_LOG_DESYEAR.payee_account_name is '收款人名称'@\
comment on column EBANK_CORE_LOG_DESYEAR.payee_account_bank is '收款人银行'@\
comment on column EBANK_CORE_LOG_DESYEAR.pay_money is '支付金额'@\
comment on column EBANK_CORE_LOG_DESYEAR.agent_business_no is '交易流水号'@\
comment on column EBANK_CORE_LOG_DESYEAR.process_status is '处理状态 : 0，未处理；1,处理中； 2处理完成 '@\
comment on column EBANK_CORE_LOG_DESYEAR.errormsg is '出错信息'@\
comment on column EBANK_CORE_LOG_DESYEAR.is_success is '交易是否成功：0，失败；1成功'@\
comment on column EBANK_CORE_LOG_DESYEAR.tran_teller_no is '交易柜员'@\
comment on column EBANK_CORE_LOG_DESYEAR.tran_branch_id is '交易机构'@\
comment on column EBANK_CORE_LOG_DESYEAR.tran_amt is '交易金额'@\
comment on column EBANK_CORE_LOG_DESYEAR.tran_date is '交易日期'@\
comment on column EBANK_CORE_LOG_DESYEAR.tran_remark is '交易摘要'@\
comment on column EBANK_CORE_LOG_DESYEAR.crdtle_flag is '抹账标志，0 未抹账  1 已抹账'@\
comment on column EBANK_CORE_LOG_DESYEAR.errorcode is '错误代码'@\
comment on column EBANK_CORE_LOG_DESYEAR.file_name is '待扩展'@\
comment on column EBANK_CORE_LOG_DESYEAR.accept_number is '待扩展'@\
comment on column EBANK_CORE_LOG_DESYEAR.seq_no is '提交交易系统流水号'
SQL_CREATE_COMMENT_EBANK_DAY_BILL = comment on column EBANK_DAY_BILL_DESYEAR.id is '主键'@\
comment on column EBANK_DAY_BILL_DESYEAR.bill_no is '凭证编号'@\
comment on column EBANK_DAY_BILL_DESYEAR.pay_money is '支付金额'@\
comment on column EBANK_DAY_BILL_DESYEAR.pos_money is '支款金额'@\
comment on column EBANK_DAY_BILL_DESYEAR.neg_money is '退款金额'@\
comment on column EBANK_DAY_BILL_DESYEAR.bl_code is '指标来源编码'@\
comment on column EBANK_DAY_BILL_DESYEAR.bl_name is '指标来源名称'@\
comment on column EBANK_DAY_BILL_DESYEAR.pb_code is '代理银行编码'@\
comment on column EBANK_DAY_BILL_DESYEAR.pb_name is '代理银行名称'@\
comment on column EBANK_DAY_BILL_DESYEAR.mk_code is '资金性质编码'@\
comment on column EBANK_DAY_BILL_DESYEAR.mk_name is '资金性质名称'@\
comment on column EBANK_DAY_BILL_DESYEAR.pk_code is '支付方式编码'@\
comment on column EBANK_DAY_BILL_DESYEAR.pk_name is '支付方式名称'@\
comment on column EBANK_DAY_BILL_DESYEAR.create_date is '生成日期'@\
comment on column EBANK_DAY_BILL_DESYEAR.is_valid is '是否有效'@\
comment on column EBANK_DAY_BILL_DESYEAR.confirm_date is '确认日期'@\
comment on column EBANK_DAY_BILL_DESYEAR.confirm_user is '确认用户'@\
comment on column EBANK_DAY_BILL_DESYEAR.set_year is '年度'@\
comment on column EBANK_DAY_BILL_DESYEAR.finance_code is '区划'@\
comment on column EBANK_DAY_BILL_DESYEAR.hold1 is '预算字段1'@\
comment on column EBANK_DAY_BILL_DESYEAR.hold2 is '预算字段2'@\
comment on column EBANK_DAY_BILL_DESYEAR.hold3 is '预算字段3'@\
comment on column EBANK_DAY_BILL_DESYEAR.hold4 is '预算字段4'@\
comment on column EBANK_DAY_BILL_DESYEAR.print_date is '打印日期'@\
comment on column EBANK_DAY_BILL_DESYEAR.print_num is '打印次数'@\
comment on column EBANK_DAY_BILL_DESYEAR.print_user is '打印用户'@\
comment on column EBANK_DAY_BILL_DESYEAR.send_operator is '签章发送操作人员'@\
comment on column EBANK_DAY_BILL_DESYEAR.create_operator is '生成人'@\
comment on column EBANK_DAY_BILL_DESYEAR.vt_code is '凭证类型'
SQL_CREATE_COMMENT_EBANK_PAY_BATCH_BILL = comment on table EBANK_PAY_BATCH_BILL_DESYEAR is '支付凭证单据表'@\ 
comment on column EBANK_PAY_BATCH_BILL_DESYEAR.id is '主键'@\
comment on column EBANK_PAY_BATCH_BILL_DESYEAR.bill_no is '支付凭证号'@\
comment on column EBANK_PAY_BATCH_BILL_DESYEAR.set_year is '年度'@\
comment on column EBANK_PAY_BATCH_BILL_DESYEAR.vt_code is '交易凭证类型'@\
comment on column EBANK_PAY_BATCH_BILL_DESYEAR.pay_money is '汇总金额'@\
comment on column EBANK_PAY_BATCH_BILL_DESYEAR.ori_vt_code is '主凭证类型编号'@\
comment on column EBANK_PAY_BATCH_BILL_DESYEAR.ori_bill_no is '主支付凭证编号'@\
comment on column EBANK_PAY_BATCH_BILL_DESYEAR.finance_code is '财政机构'@\
comment on column EBANK_PAY_BATCH_BILL_DESYEAR.en_code is '预算单位编码'@\
comment on column EBANK_PAY_BATCH_BILL_DESYEAR.en_name is '预算单位编码'@\
comment on column EBANK_PAY_BATCH_BILL_DESYEAR.pay_account_no is '付款人账号'@\
comment on column EBANK_PAY_BATCH_BILL_DESYEAR.pay_account_name is '付款人名称'@\
comment on column EBANK_PAY_BATCH_BILL_DESYEAR.pay_account_bank_name is '付款人银行'@\
comment on column EBANK_PAY_BATCH_BILL_DESYEAR.pay_bank_code is '代理银行编码'@\
comment on column EBANK_PAY_BATCH_BILL_DESYEAR.pay_bank_name is '代理银行名称'@\
comment on column EBANK_PAY_BATCH_BILL_DESYEAR.xpay_date is '实际凭证确认日期'@\
comment on column EBANK_PAY_BATCH_BILL_DESYEAR.xpay_money is '实际支付汇总金额'@\
comment on column EBANK_PAY_BATCH_BILL_DESYEAR.pm_code is '结算方式代码'@\
comment on column EBANK_PAY_BATCH_BILL_DESYEAR.pf_code is '支付管理类型代码'@\
comment on column EBANK_PAY_BATCH_BILL_DESYEAR.operator is '操作人'@\
comment on column EBANK_PAY_BATCH_BILL_DESYEAR.send_date is '签章发送时间'@\
comment on column EBANK_PAY_BATCH_BILL_DESYEAR.send_operator is '签章发送操作人'@\
comment on column EBANK_PAY_BATCH_BILL_DESYEAR.work_flow_entity_id is '工作流关联字段'@\
comment on column EBANK_PAY_BATCH_BILL_DESYEAR.voucher_receive_date is '凭证签收日期'
SQL_CREATE_COMMENT_EBANK_PAY_BATCH_DETAIL = comment on table EBANK_PAY_BATCH_DETAIL_DESYEAR is '支付凭证'@\ 
comment on column EBANK_PAY_BATCH_DETAIL_DESYEAR.id is '主键'@\
comment on column EBANK_PAY_BATCH_DETAIL_DESYEAR.bill_no is '支付主单编号'@\
comment on column EBANK_PAY_BATCH_DETAIL_DESYEAR.payee_account_no is '收款人账户编号'@\
comment on column EBANK_PAY_BATCH_DETAIL_DESYEAR.payee_account_name is '收款人账户名称'@\
comment on column EBANK_PAY_BATCH_DETAIL_DESYEAR.payee_account_bank is '收款人账户银行'@\
comment on column EBANK_PAY_BATCH_DETAIL_DESYEAR.finance_code is '财政机构'@\
comment on column EBANK_PAY_BATCH_DETAIL_DESYEAR.pay_money is '计划金额'@\
comment on column EBANK_PAY_BATCH_DETAIL_DESYEAR.remark is '备注'@\
comment on column EBANK_PAY_BATCH_DETAIL_DESYEAR.xpay_date is '支付日期'@\
comment on column EBANK_PAY_BATCH_DETAIL_DESYEAR.xagent_business_no is '银行交易流水号'@\
comment on column EBANK_PAY_BATCH_DETAIL_DESYEAR.xpay_money is '计划金额'@\
comment on column EBANK_PAY_BATCH_DETAIL_DESYEAR.xpayee_account_no is '收款人账户编号'@\
comment on column EBANK_PAY_BATCH_DETAIL_DESYEAR.xpayee_account_bank_name is '收款人账户名称'@\
comment on column EBANK_PAY_BATCH_DETAIL_DESYEAR.hold1 is '预留字段1'@\
comment on column EBANK_PAY_BATCH_DETAIL_DESYEAR.hold2 is '预留字段2'@\
comment on column EBANK_PAY_BATCH_DETAIL_DESYEAR.hold3 is '预留字段3'@\
comment on column EBANK_PAY_BATCH_DETAIL_DESYEAR.hold4 is '预留字段4'@\
comment on column EBANK_PAY_BATCH_DETAIL_DESYEAR.set_year is '年度'@\
comment on column EBANK_PAY_BATCH_DETAIL_DESYEAR.bill_status is '1:待支付 2：支付成功 3：支付失败 4：退款'@\
comment on column EBANK_PAY_BATCH_DETAIL_DESYEAR.message is '支付失败原因'
SQL_CREATE_COMMENT_EBANK_PAY_BILL = comment on column EBANK_PAY_BILL_DESYEAR.id is '主键'@\
comment on column EBANK_PAY_BILL_DESYEAR.bill_no is '凭证编号'@\
comment on column EBANK_PAY_BILL_DESYEAR.set_year is '年度'@\
comment on column EBANK_PAY_BILL_DESYEAR.bi_code is '项目分类编码'@\
comment on column EBANK_PAY_BILL_DESYEAR.bi_name is '项目分类名称'@\
comment on column EBANK_PAY_BILL_DESYEAR.bis_code is '预算项目编码'@\
comment on column EBANK_PAY_BILL_DESYEAR.bis_name is '预算项目名称'@\
comment on column EBANK_PAY_BILL_DESYEAR.bo_code is '核算类型编码'@\
comment on column EBANK_PAY_BILL_DESYEAR.bo_name is '核算类型名称'@\
comment on column EBANK_PAY_BILL_DESYEAR.bs_code1 is '功能科目（类）编码'@\
comment on column EBANK_PAY_BILL_DESYEAR.bs_name1 is '功能科目（类）名称'@\
comment on column EBANK_PAY_BILL_DESYEAR.bs_code2 is '功能科目（款）编码'@\
comment on column EBANK_PAY_BILL_DESYEAR.bs_name2 is '功能科目（款）名称'@\
comment on column EBANK_PAY_BILL_DESYEAR.bs_code3 is '功能科目（项）编码'@\
comment on column EBANK_PAY_BILL_DESYEAR.bs_name3 is '功能科目（项）名称'@\
comment on column EBANK_PAY_BILL_DESYEAR.bsi_code is '经济科目编码'@\
comment on column EBANK_PAY_BILL_DESYEAR.bsi_name is '经济科目名称'@\
comment on column EBANK_PAY_BILL_DESYEAR.en_code1 is '主管预算单位编码'@\
comment on column EBANK_PAY_BILL_DESYEAR.en_name1 is '主管预算单位名称'@\
comment on column EBANK_PAY_BILL_DESYEAR.en_code is '基层预算单位编码'@\
comment on column EBANK_PAY_BILL_DESYEAR.en_name is '基层预算单位名称'@\
comment on column EBANK_PAY_BILL_DESYEAR.mk_code is '资金性质编码'@\
comment on column EBANK_PAY_BILL_DESYEAR.mk_name is '资金性质名称'@\
comment on column EBANK_PAY_BILL_DESYEAR.payee_account_no is '收款人账号'@\
comment on column EBANK_PAY_BILL_DESYEAR.payee_account_name is '收款人名称'@\
comment on column EBANK_PAY_BILL_DESYEAR.payee_account_bank is '收款人开户行'@\
comment on column EBANK_PAY_BILL_DESYEAR.pay_account_no is '付款人账号'@\
comment on column EBANK_PAY_BILL_DESYEAR.pay_account_name is '付款人名称'@\
comment on column EBANK_PAY_BILL_DESYEAR.pay_account_bank is '付款人开户行'@\
comment on column EBANK_PAY_BILL_DESYEAR.pay_money is '支付金额'@\
comment on column EBANK_PAY_BILL_DESYEAR.pay_summary_code is '支付摘要编码'@\
comment on column EBANK_PAY_BILL_DESYEAR.pay_summary_name is '支付摘要名称'@\
comment on column EBANK_PAY_BILL_DESYEAR.pf_code is '支付管理类型编码'@\
comment on column EBANK_PAY_BILL_DESYEAR.pf_name is '支付管理类型名称'@\
comment on column EBANK_PAY_BILL_DESYEAR.pk_code is '支付方式编码'@\
comment on column EBANK_PAY_BILL_DESYEAR.pk_name is '支付方式名称'@\
comment on column EBANK_PAY_BILL_DESYEAR.pm_code is '结算方式编码'@\
comment on column EBANK_PAY_BILL_DESYEAR.pm_name is '结算方式名称'@\
comment on column EBANK_PAY_BILL_DESYEAR.print_date is '打印日期'@\
comment on column EBANK_PAY_BILL_DESYEAR.hold1 is '预算字段1'@\
comment on column EBANK_PAY_BILL_DESYEAR.hold2 is '预算字段2'@\
comment on column EBANK_PAY_BILL_DESYEAR.hold3 is '预算字段3'@\
comment on column EBANK_PAY_BILL_DESYEAR.hold4 is '预算字段4'@\
comment on column EBANK_PAY_BILL_DESYEAR.agent_account_no is '划款账户账号'@\
comment on column EBANK_PAY_BILL_DESYEAR.agent_account_name is '划款账户名称'@\
comment on column EBANK_PAY_BILL_DESYEAR.agent_account_bank is '划款账户开户行'@\
comment on column EBANK_PAY_BILL_DESYEAR.agent_business_no is '交易流水号'@\
comment on column EBANK_PAY_BILL_DESYEAR.billtype_code is '单据类型  1-直接   2-授权'@\
comment on column EBANK_PAY_BILL_DESYEAR.check_no is '支票号'@\
comment on column EBANK_PAY_BILL_DESYEAR.clear_date is '清算日期'@\
comment on column EBANK_PAY_BILL_DESYEAR.confirm_user is '确认用户'@\
comment on column EBANK_PAY_BILL_DESYEAR.create_date is '生成日期'@\
comment on column EBANK_PAY_BILL_DESYEAR.is_end is '是否结束'@\
comment on column EBANK_PAY_BILL_DESYEAR.is_valid is '是否有效'@\
comment on column EBANK_PAY_BILL_DESYEAR.origin_model is '业务标示'@\
comment on column EBANK_PAY_BILL_DESYEAR.pay_date is '支付日期'@\
comment on column EBANK_PAY_BILL_DESYEAR.plan_id is '计划额度ID'@\
comment on column EBANK_PAY_BILL_DESYEAR.input_money is '原金额'@\
comment on column EBANK_PAY_BILL_DESYEAR.agent_bill_no is '划款单号'@\
comment on column EBANK_PAY_BILL_DESYEAR.day_bill_no is '日报单号'@\
comment on column EBANK_PAY_BILL_DESYEAR.acc_bill_no is '入账通知书单号'@\
comment on column EBANK_PAY_BILL_DESYEAR.refund_type is '退款类型'@\
comment on column EBANK_PAY_BILL_DESYEAR.ori_bill_no is '原凭证号'@\
comment on column EBANK_PAY_BILL_DESYEAR.remark is '备注信息'@\
comment on column EBANK_PAY_BILL_DESYEAR.pb_code is '代理银行编码'@\
comment on column EBANK_PAY_BILL_DESYEAR.pb_name is '代理银行名称'@\
comment on column EBANK_PAY_BILL_DESYEAR.bs_code is '功能科目编码'@\
comment on column EBANK_PAY_BILL_DESYEAR.bs_name is '功能科目名称'@\
comment on column EBANK_PAY_BILL_DESYEAR.payee_bank_no is '收款行号'@\
comment on column EBANK_PAY_BILL_DESYEAR.finance_code is '财政机构'@\
comment on column EBANK_PAY_BILL_DESYEAR.bill_status is '凭证业务状态：0 签收，1 已垫款，2 支付，3 已回单，4 已清算，5 已退回 ，6垫款状态确认（重庆银行特色），7撤销垫款但未进行撤销垫款状态确认（重庆银行特色），8自助柜面支付失败'@\
comment on column EBANK_PAY_BILL_DESYEAR.advince is '退回财政原因'@\
comment on column EBANK_PAY_BILL_DESYEAR.advance_operator is '垫款操作人员'@\
comment on column EBANK_PAY_BILL_DESYEAR.advance_date is '垫款时间'@\
comment on column EBANK_PAY_BILL_DESYEAR.confirm_advance_operator is '垫款状态确认或审核人员'@\
comment on column EBANK_PAY_BILL_DESYEAR.confirm_advance_date is '垫款状态确认时间'@\
comment on column EBANK_PAY_BILL_DESYEAR.cancel_advance_operator is '撤销垫款人员'@\
comment on column EBANK_PAY_BILL_DESYEAR.cancel_advance_date is '撤销垫款时间'@\
comment on column EBANK_PAY_BILL_DESYEAR.return_operator is '退回财政操作人'@\
comment on column EBANK_PAY_BILL_DESYEAR.return_date is '退回财政时间'@\
comment on column EBANK_PAY_BILL_DESYEAR.send_operator is '签章发送操作人员'@\
comment on column EBANK_PAY_BILL_DESYEAR.create_operator is '录入操作人员'@\
comment on column EBANK_PAY_BILL_DESYEAR.pay_operator is '审核人员'@\
comment on column EBANK_PAY_BILL_DESYEAR.cancel_check_operator is '撤销审核人员'@\
comment on column EBANK_PAY_BILL_DESYEAR.cancel_check_date is '撤销审核时间'@\
comment on column EBANK_PAY_BILL_DESYEAR.delete_bill_operator is '作废操作人'@\
comment on column EBANK_PAY_BILL_DESYEAR.delete_bill_date is '作废时间'@\
comment on column EBANK_PAY_BILL_DESYEAR.xpayee_account_no is '收款人账号'@\
comment on column EBANK_PAY_BILL_DESYEAR.xpayee_account_name is '收款人名称'@\
comment on column EBANK_PAY_BILL_DESYEAR.xpayee_account_bank is '收款人银行'@\
comment on column EBANK_PAY_BILL_DESYEAR.mode_code is '1柜面业务2.自助柜面业务'@\
comment on column EBANK_PAY_BILL_DESYEAR.mode_name is '1柜面业务2.自助柜面业务'@\
comment on column EBANK_PAY_BILL_DESYEAR.business_type_code is '业务类型编码 '@\
comment on column EBANK_PAY_BILL_DESYEAR.business_type_name is '业务类型名称'@\
comment on column EBANK_PAY_BILL_DESYEAR.vt_code is '凭证类型'@\
comment on column EBANK_PAY_BILL_DESYEAR.refund_money is '已退金额'@\
comment on column EBANK_PAY_BILL_DESYEAR.advance_no is '垫款户账号'@\
comment on column EBANK_PAY_BILL_DESYEAR.advance_name is '垫款户名称'@\
comment on column EBANK_PAY_BILL_DESYEAR.voucher_receive_date is '凭证签收日期'@\
comment on column EBANK_PAY_BILL_DESYEAR.exchange_text is '记录交换中心返回数据'
SQL_CREATE_COMMENT_EBANK_PAY_DETAIL = comment on column EBANK_PAY_DETAIL_DESYEAR.id is '主键'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.clear_bill_id is '汇总清算单ID'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.voucher_no is '支付明细编号'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.voucher_bill_id is '支付凭证id'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.voucher_bill_no is '支付凭证单号'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.en_name is '预算单位名称'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.bs_name is '功能科目名称'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.hold1 is '预留字段1'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.hold2 is '预留字段2'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.hold3 is '预留字段3'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.hold4 is '预留字段4'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.en_code is '预算单位编码'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.bs_code is '功能科目编码'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.pay_money is '支付金额'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.set_year is '年度'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.bap_name is '支付账户'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.finance_code is '财政机构'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.bis_code is '预算项目编码'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.bis_name is '预算项目名称'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.bi_code is '项目分类编码'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.bi_name is '项目分类名称'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.bo_code is '预算类型编码'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.bo_name is '预算类型名称'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.bsi_code is '经济分类编码'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.bsi_name is '经济分类名称'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.check_no is '支票号（结算号）'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.en_code1 is '一级预算单位编码'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.old_pay_id is '退款明细旧id'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.refund_money is '退款金额'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.agent_bill_id is '划款单ID'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.acc_bill_id is '入账通知书id'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.acc_bill_no is '入账通知书凭证编号'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.day_bill_id is '支出日报id'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.create_date is '创建日期'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.business_type_code is '业务类型编码'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.business_type_name is '业务类型名称'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.mb_code is '业务处室编码'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.mb_name is '业务处室'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.bp_code is '指标特性编码'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.bp_name is '指标特性'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.input_money is '原始金额'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.ori_voucher_no is '原退款明细单号'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.is_end is '1完成清算'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.bap_code is '支付账户编码'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.agent_bill_no is '划款单号'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.day_bill_no is '支付日报表单号'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.mode_code is '1柜面业务，2自助柜面业务'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.work_flow_entity_id is '工作流关联id'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.sum_id is '额度扣除字段'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.advance_no is '垫款户账号'@\
comment on column EBANK_PAY_DETAIL_DESYEAR.advance_name is '垫款户名称'
SQL_CREATE_COMMENT_EBANK_PAYCARD_BILL = comment on table EBANK_PAYCARD_BILL_DESYEAR is '公务卡凭证单据主单'@\
comment on column EBANK_PAYCARD_BILL_DESYEAR.id is '主单Id（卡信息单ID、变更单ID、注销单ID）'@\
comment on column EBANK_PAYCARD_BILL_DESYEAR.finance_code is '财政机构代码'@\
comment on column EBANK_PAYCARD_BILL_DESYEAR.budgetlevelcode is '预算级次'@\
comment on column EBANK_PAYCARD_BILL_DESYEAR.set_year is '业务年度'@\
comment on column EBANK_PAYCARD_BILL_DESYEAR.cardyear is '开卡年度'@\
comment on column EBANK_PAYCARD_BILL_DESYEAR.billtype_code is '凭证单据类型编号'@\
comment on column EBANK_PAYCARD_BILL_DESYEAR.voudate is '凭证日期（时间 格式：yyyy-MM-dd hh24:mi:ss）'@\
comment on column EBANK_PAYCARD_BILL_DESYEAR.voucherno is '凭证号（公务卡单据单号，卡信息单号、变更单号、注销单号）'@\
comment on column EBANK_PAYCARD_BILL_DESYEAR.cardbankid is '发卡行ID'@\
comment on column EBANK_PAYCARD_BILL_DESYEAR.cardbankcode is '发卡行编码'@\
comment on column EBANK_PAYCARD_BILL_DESYEAR.cardbankname is '发卡行名称'@\
comment on column EBANK_PAYCARD_BILL_DESYEAR.hold1 is '预留字段1（基本信息）'@\
comment on column EBANK_PAYCARD_BILL_DESYEAR.hold2 is '预留字段2（基本信息）'@\
comment on column EBANK_PAYCARD_BILL_DESYEAR.hold3 is '预留字段3（基本信息）'@\
comment on column EBANK_PAYCARD_BILL_DESYEAR.hold4 is '预留字段4（基本信息）'@\
comment on column EBANK_PAYCARD_BILL_DESYEAR.remark is '备注'@\
comment on column EBANK_PAYCARD_BILL_DESYEAR.ts is '时间戳（时间 格式：yyyy-MM-dd hh24:mi:ss）'@\
comment on column EBANK_PAYCARD_BILL_DESYEAR.is_valid is '是否有效'@\
comment on column EBANK_PAYCARD_BILL_DESYEAR.is_end is '流程是否结束'@\
comment on column EBANK_PAYCARD_BILL_DESYEAR.cardno is '公务卡卡号'@\
comment on column EBANK_PAYCARD_BILL_DESYEAR.requestbillno is '下载请求单号（对应公务卡消费明细下载请求单号）'@\
comment on column EBANK_PAYCARD_BILL_DESYEAR.serialno is '消费授权号（消费小票上的授权号或流水号）'@\
comment on column EBANK_PAYCARD_BILL_DESYEAR.consumedate is '消费日期（时间 格式：yyyy-MM-dd hh24:mi:ss）'@\
comment on column EBANK_PAYCARD_BILL_DESYEAR.consumemoney is '消费金额[消费的实际金额]'@\
comment on column EBANK_PAYCARD_BILL_DESYEAR.downloadtype is '下载类型消费记录下载的请求条件组合类型【1：授权号、2：消费日期+消费金额】'@\
comment on column EBANK_PAYCARD_BILL_DESYEAR.agencyid is '预算单位ID'@\
comment on column EBANK_PAYCARD_BILL_DESYEAR.agencycode is '预算单位编码'@\
comment on column EBANK_PAYCARD_BILL_DESYEAR.hold5 is '预留字段1（消费信息）'@\
comment on column EBANK_PAYCARD_BILL_DESYEAR.hold6 is '预留字段2（消费信息）'@\
comment on column EBANK_PAYCARD_BILL_DESYEAR.hold7 is '预留字段3（消费信息）'@\
comment on column EBANK_PAYCARD_BILL_DESYEAR.hold8 is '预留字段4（消费信息）'@\
comment on column EBANK_PAYCARD_BILL_DESYEAR.origin_model is '来源标志：0：为录入 1：导入'@\
comment on column EBANK_PAYCARD_BILL_DESYEAR.sortcode is '排序码'
SQL_CREATE_COMMENT_EBANK_PAYCARD_BILL_DETAIL = comment on table EBANK_PAYCARD_BILL_DETAIL_DESYEAR is '公务卡凭证单据明细单'@\ 
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.id is '明细Id（流水号）'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.cardbillid is '主单Id（与主单id内容一致）'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.finance_code is '财政机构代码'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.set_year is '业务年度'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.billtype_code is '凭证单据类型编号'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.cardholder is '持卡人姓名'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.cardholderrank is '持卡人职级'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.cardholderno is '身份证号码'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.agencyid is '预算单位ID（新）'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.agencycode is '预算单位编码（新）'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.agencyname is '预算单位名称（新）'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.cardid is '公务卡ID（新）'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.cardno is '公务卡卡号（新）'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.creditnum is '信用额度'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.mobilenum is '持卡人手机号'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.cardmadedate is '制卡日期（时间 格式：yyyy-MM-dd hh24:mi:ss）'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.cardtype is '公务卡类型（1 个人卡  2单位卡）'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.cardstatus is '卡状态（新）（1正常、2停用、3注销）'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.cardbegindate is '开卡日期（时间 格式：yyyy-MM-dd hh24:mi:ss）'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.cardenddate is '停用日期（时间 格式：yyyy-MM-dd hh24:mi:ss）'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.hold1 is '预留字段1（基本信息）'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.hold2 is '预留字段2（基本信息）'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.hold3 is '预留字段3（基本信息）'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.hold4 is '预留字段4（基本信息）'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.cardchangetype is '变更类型（0手工录入，1换卡号，2换单位，3变更卡状态，4Excel导入）'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.cardchangedate is '变更日期（时间 格式：yyyy-MM-dd hh24:mi:ss）'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.oldcardid is '原公务卡ID'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.oldcardno is '原公务卡卡号'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.oldagencyid is '原预算单位编码'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.oldagencycode is '原预算单位编码'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.oldagencyname is '原预算单位名称'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.oldcardstatus is '原卡状态（1正常、2停用、3注销）'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.remark is '备注'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.ts is '时间戳（时间 格式：yyyy-MM-dd hh24:mi:ss）'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.is_valid is '是否有效'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.is_end is '流程是否结束'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.consume_time is '消费时间（时间 格式：yyyy-MM-dd hh24:mi:ss）'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.serialno is '消费授权号（消费小票上的授权号或流水号）'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.consumemoney is '消费金额[消费的实际金额]'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.merchant_name is '消费商家名称'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.transaction_addr is '消费商家地址'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.cardbankname is '发卡行名称'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.cardbankcode is '发卡行编码'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.cardbankid is '发卡行ID'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.hold5 is '预留字段1（消费信息）'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.hold6 is '预留字段2（消费信息）'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.hold7 is '预留字段3（消费信息）'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.hold8 is '预留字段4（消费信息）'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.origin_model is '来源标志：0：为录入 1：导入'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.opcountsucess is '操作成功次数计算器'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.opcountfail is '操作失败次数计数器'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.reason is '操作后返回的成功或失败消息和原因'@\
comment on column EBANK_PAYCARD_BILL_DETAIL_DESYEAR.sortcode is '排序码'
SQL_CREATE_COMMENT_EBANK_PLAN_AGENT_BILL = comment on column EBANK_PLAN_AGENT_BILL_DESYEAR.id is 'id'@\
comment on column EBANK_PLAN_AGENT_BILL_DESYEAR.bill_no is '凭证号'@\
comment on column EBANK_PLAN_AGENT_BILL_DESYEAR.create_date is '凭证日期'@\
comment on column EBANK_PLAN_AGENT_BILL_DESYEAR.finance_code is '财政'@\
comment on column EBANK_PLAN_AGENT_BILL_DESYEAR.set_year is '年度'@\
comment on column EBANK_PLAN_AGENT_BILL_DESYEAR.vt_code is '凭证类型'@\
comment on column EBANK_PLAN_AGENT_BILL_DESYEAR.mk_code is '资金性质编码'@\
comment on column EBANK_PLAN_AGENT_BILL_DESYEAR.mk_name is '资金性质名称'@\
comment on column EBANK_PLAN_AGENT_BILL_DESYEAR.pb_code is '代理银行编码'@\
comment on column EBANK_PLAN_AGENT_BILL_DESYEAR.pb_name is '代理银行名称'@\
comment on column EBANK_PLAN_AGENT_BILL_DESYEAR.set_month is '月份'@\
comment on column EBANK_PLAN_AGENT_BILL_DESYEAR.plan_money is '金额'@\
comment on column EBANK_PLAN_AGENT_BILL_DESYEAR.en_code1_num is '一级预算单位数量'@\
comment on column EBANK_PLAN_AGENT_BILL_DESYEAR.remark is '附言'@\
comment on column EBANK_PLAN_AGENT_BILL_DESYEAR.xacct_date is '处理日期'@\
comment on column EBANK_PLAN_AGENT_BILL_DESYEAR.bis_code is '预算项目编码'@\
comment on column EBANK_PLAN_AGENT_BILL_DESYEAR.bis_name is '预算项目名称'@\
comment on column EBANK_PLAN_AGENT_BILL_DESYEAR.send_date is '签章发送日期'@\
comment on column EBANK_PLAN_AGENT_BILL_DESYEAR.send_operator is '签章发送操作人员'@\
comment on column EBANK_PLAN_AGENT_BILL_DESYEAR.create_operator is '生成人'@\
comment on column EBANK_PLAN_AGENT_BILL_DESYEAR.voucher_receive_date is '凭证签收日期'
SQL_CREATE_COMMENT_EBANK_PLAN_AGENTEN_BILL = comment on column EBANK_PLAN_AGENTEN_BILL_DESYEAR.id is '财政授权支付额度到账通知书Id'@\
comment on column EBANK_PLAN_AGENTEN_BILL_DESYEAR.rg_code is '行政区划代码'@\
comment on column EBANK_PLAN_AGENTEN_BILL_DESYEAR.set_year is '业务年度'@\
comment on column EBANK_PLAN_AGENTEN_BILL_DESYEAR.create_date is '凭证日期'@\
comment on column EBANK_PLAN_AGENTEN_BILL_DESYEAR.bill_no is '凭证号'@\
comment on column EBANK_PLAN_AGENTEN_BILL_DESYEAR.bis_code is '预算类型编码'@\
comment on column EBANK_PLAN_AGENTEN_BILL_DESYEAR.bis_name is '预算类型名称'@\
comment on column EBANK_PLAN_AGENTEN_BILL_DESYEAR.mk_code is '资金性质编码'@\
comment on column EBANK_PLAN_AGENTEN_BILL_DESYEAR.mk_name is '资金性质名称'@\
comment on column EBANK_PLAN_AGENTEN_BILL_DESYEAR.en_code1 is '一级预算单位编码'@\
comment on column EBANK_PLAN_AGENTEN_BILL_DESYEAR.en_name1 is '一级预算单位名称'@\
comment on column EBANK_PLAN_AGENTEN_BILL_DESYEAR.en_name is '基层预算单位名称'@\
comment on column EBANK_PLAN_AGENTEN_BILL_DESYEAR.en_code is '基层预算单位编码'@\
comment on column EBANK_PLAN_AGENTEN_BILL_DESYEAR.plan_money is '汇总计划金额'@\
comment on column EBANK_PLAN_AGENTEN_BILL_DESYEAR.set_month is '计划月份'@\
comment on column EBANK_PLAN_AGENTEN_BILL_DESYEAR.pb_code is '代理银行编码'@\
comment on column EBANK_PLAN_AGENTEN_BILL_DESYEAR.pb_name is '代理银行名称'@\
comment on column EBANK_PLAN_AGENTEN_BILL_DESYEAR.agency_acco_code is '单位零余额账户'@\
comment on column EBANK_PLAN_AGENTEN_BILL_DESYEAR.agency_acco_name is '单位零余额账户名称'@\
comment on column EBANK_PLAN_AGENTEN_BILL_DESYEAR.agency_bank_no is '单位零余额开户银行行号'@\
comment on column EBANK_PLAN_AGENTEN_BILL_DESYEAR.agency_bank_name is '单位零余额开户银行名称'@\
comment on column EBANK_PLAN_AGENTEN_BILL_DESYEAR.vt_code is '凭证类型编号'@\
comment on column EBANK_PLAN_AGENTEN_BILL_DESYEAR.send_operator is '签章发送操作人员'@\
comment on column EBANK_PLAN_AGENTEN_BILL_DESYEAR.create_operator is '生成人'
SQL_CREATE_COMMENT_EBANK_PLAN_VOUCHER = comment on column EBANK_PLAN_VOUCHER_DESYEAR.id is '计划明细Id'@\
comment on column EBANK_PLAN_VOUCHER_DESYEAR.voucher_no is '计划明细编号'@\
comment on column EBANK_PLAN_VOUCHER_DESYEAR.agent_bill_id is '财政授权支付额度通知单Id'@\
comment on column EBANK_PLAN_VOUCHER_DESYEAR.agenten_bill_id is '额度到账通知书id'@\
comment on column EBANK_PLAN_VOUCHER_DESYEAR.bis_code is '预算类型编码'@\
comment on column EBANK_PLAN_VOUCHER_DESYEAR.bis_name is '预算类型名称'@\
comment on column EBANK_PLAN_VOUCHER_DESYEAR.mk_code is '资金性质编码'@\
comment on column EBANK_PLAN_VOUCHER_DESYEAR.mk_name is '资金性质名称'@\
comment on column EBANK_PLAN_VOUCHER_DESYEAR.en_code is '基层预算单位编码'@\
comment on column EBANK_PLAN_VOUCHER_DESYEAR.en_name is '基层预算单位名称'@\
comment on column EBANK_PLAN_VOUCHER_DESYEAR.en_code1 is '一级预算单位编码'@\
comment on column EBANK_PLAN_VOUCHER_DESYEAR.en_name1 is '一级预算单位名称'@\
comment on column EBANK_PLAN_VOUCHER_DESYEAR.bs_code is '支出功能分类科目编码'@\
comment on column EBANK_PLAN_VOUCHER_DESYEAR.bs_name is '支出功能分类科目名称'@\
comment on column EBANK_PLAN_VOUCHER_DESYEAR.bs_code1 is '支出功能分类类编码'@\
comment on column EBANK_PLAN_VOUCHER_DESYEAR.bs_name1 is '支出功能分类类名称'@\
comment on column EBANK_PLAN_VOUCHER_DESYEAR.bs_code2 is '支出功能分类款编码'@\
comment on column EBANK_PLAN_VOUCHER_DESYEAR.bs_name2 is '支出功能分类款名称'@\
comment on column EBANK_PLAN_VOUCHER_DESYEAR.bs_code3 is '支出功能分类项编码'@\
comment on column EBANK_PLAN_VOUCHER_DESYEAR.bs_name3 is '支出功能分类项名称'@\
comment on column EBANK_PLAN_VOUCHER_DESYEAR.inpm_code is '收支管理编码'@\
comment on column EBANK_PLAN_VOUCHER_DESYEAR.inpm_name is '收支管理名称'@\
comment on column EBANK_PLAN_VOUCHER_DESYEAR.tracking_id is '业务追溯识别码'@\
comment on column EBANK_PLAN_VOUCHER_DESYEAR.plan_money is '额度金额'@\
comment on column EBANK_PLAN_VOUCHER_DESYEAR.remark is '备注'@\
comment on column EBANK_PLAN_VOUCHER_DESYEAR.agency_acco_code is '单位零余额账户'@\
comment on column EBANK_PLAN_VOUCHER_DESYEAR.agency_acco_name is '单位零余额账户名称'@\
comment on column EBANK_PLAN_VOUCHER_DESYEAR.agency_bank_name is '单位零余额帐户开户行'@\
comment on column EBANK_PLAN_VOUCHER_DESYEAR.bsi_code is '经济分类科目编码'@\
comment on column EBANK_PLAN_VOUCHER_DESYEAR.bsi_name is '经济分类科目名称'@\
comment on column EBANK_PLAN_VOUCHER_DESYEAR.rg_code is '行政区划代码'@\
comment on column EBANK_PLAN_VOUCHER_DESYEAR.set_year is '业务年度'@\
comment on column EBANK_PLAN_VOUCHER_DESYEAR.set_month is '计划月份'@\
comment on column EBANK_PLAN_VOUCHER_DESYEAR.sum_id is '额度id'@\
comment on column EBANK_PLAN_VOUCHER_DESYEAR.work_flow_entity_id is '工作流关联id'
SQL_CREATE_COMMENT_EBANK_VOUCHER_RECEIVE_LOG = comment on table EBANK_VOUCHER_RECEIVE_LOG_DESYEAR is '电子凭证接收记录日志表'@\
comment on column EBANK_VOUCHER_RECEIVE_LOG_DESYEAR.id is '主键ID，取自序列'@\
comment on column EBANK_VOUCHER_RECEIVE_LOG_DESYEAR.finance_code is '区划'@\
comment on column EBANK_VOUCHER_RECEIVE_LOG_DESYEAR.set_year is '年度'@\
comment on column EBANK_VOUCHER_RECEIVE_LOG_DESYEAR.vt_code is '凭证类型'@\
comment on column EBANK_VOUCHER_RECEIVE_LOG_DESYEAR.voucher_no is '凭证号'@\
comment on column EBANK_VOUCHER_RECEIVE_LOG_DESYEAR.voucher_flag is '凭证类型：0,接收单，1回单， 2退回单'@\
comment on column EBANK_VOUCHER_RECEIVE_LOG_DESYEAR.voucher_status is '凭证状态：0未处理、1签收成功、2签收失败、3已退回'@\
comment on column EBANK_VOUCHER_RECEIVE_LOG_DESYEAR.voucher_date is '凭证接收日期'@\
comment on column EBANK_VOUCHER_RECEIVE_LOG_DESYEAR.last_op_date is '最后一次操作日期'@\
comment on column EBANK_VOUCHER_RECEIVE_LOG_DESYEAR.op_count is '操作次数'@\
comment on column EBANK_VOUCHER_RECEIVE_LOG_DESYEAR.back_reason is '被退回原因'@\
comment on column EBANK_VOUCHER_RECEIVE_LOG_DESYEAR.fail_reason is '处理失败原因'@\
comment on column EBANK_VOUCHER_RECEIVE_LOG_DESYEAR.message is '业务报文内容'@\
comment on column EBANK_VOUCHER_RECEIVE_LOG_DESYEAR.message_hash is '报文HASH：用于判断两条凭证报文内容是否相同'@\
comment on column EBANK_VOUCHER_RECEIVE_LOG_DESYEAR.remark is '备注'@\
comment on column EBANK_VOUCHER_RECEIVE_LOG_DESYEAR.is_valid is '是否有效'
SQL_CREATE_COMMENT_EBANK_BALANCE_ELE_DETAIL = comment on column EBANK_BALANCE_ELE_DETAIL_DESYEAR.sum_id is '额度id'@\
comment on column EBANK_BALANCE_ELE_DETAIL_DESYEAR.ele_code is '要素编码'@\
comment on column EBANK_BALANCE_ELE_DETAIL_DESYEAR.ele_name is '要素名称'@\
comment on column EBANK_BALANCE_ELE_DETAIL_DESYEAR.finance_code is '财政机构'@\
comment on column EBANK_BALANCE_ELE_DETAIL_DESYEAR.ele is '要素类型'
SQL_CREATE_COMMENT_EBANK_BALANCE_LIMIT = comment on column EBANK_BALANCE_LIMIT_DESYEAR.sum_id is '额度id'@\
comment on column EBANK_BALANCE_LIMIT_DESYEAR.avi_money is '总额度'@\
comment on column EBANK_BALANCE_LIMIT_DESYEAR.use_money is '已用额度'
SQL_CREATE_COMMENT_EBALANCE_RECEIVE_LOG = comment on table EBALANCE_RECEIVE_LOG_DESYEAR is '电子凭证接收记录日志表'@\
comment on column EBALANCE_RECEIVE_LOG_DESYEAR.id is '主键ID，取自序列'@\
comment on column EBALANCE_RECEIVE_LOG_DESYEAR.rg_code is '区划'@\
comment on column EBALANCE_RECEIVE_LOG_DESYEAR.set_year is '年度'@\
comment on column EBALANCE_RECEIVE_LOG_DESYEAR.vt_code is '凭证类型'@\
comment on column EBALANCE_RECEIVE_LOG_DESYEAR.voucher_no is '凭证号'@\
comment on column EBALANCE_RECEIVE_LOG_DESYEAR.voucher_flag is '凭证类型：1正常接收单， 2退回单'@\
comment on column EBALANCE_RECEIVE_LOG_DESYEAR.voucher_status is '凭证状态：0未处理、1签收成功、2签收失败、3已退回'@\
comment on column EBALANCE_RECEIVE_LOG_DESYEAR.voucher_date is '凭证接收日期'@\
comment on column EBALANCE_RECEIVE_LOG_DESYEAR.last_op_date is '最后一次操作日期'@\
comment on column EBALANCE_RECEIVE_LOG_DESYEAR.op_count is '操作次数'@\
comment on column EBALANCE_RECEIVE_LOG_DESYEAR.back_reason is '被退回原因'@\
comment on column EBALANCE_RECEIVE_LOG_DESYEAR.fail_reason is '处理失败原因'@\
comment on column EBALANCE_RECEIVE_LOG_DESYEAR.message is '业务报文内容'@\
comment on column EBALANCE_RECEIVE_LOG_DESYEAR.message_hash is '报文HASH：用于判断两条凭证报文内容是否相同'@\
comment on column EBALANCE_RECEIVE_LOG_DESYEAR.remark is '备注'@\
comment on column EBALANCE_RECEIVE_LOG_DESYEAR.is_valid is '是否有效'
SQL_CREATE_COMMENT_EBALANCE_RECON_BILL = comment on column EBALANCE_RECON_BILL_DESYEAR.rg_code is '区划'@\
comment on column EBALANCE_RECON_BILL_DESYEAR.set_year is '年度'@\
comment on column EBALANCE_RECON_BILL_DESYEAR.vt_code is '凭证类型'@\
comment on column EBALANCE_RECON_BILL_DESYEAR.create_date is '创建时间'@\
comment on column EBALANCE_RECON_BILL_DESYEAR.voucher_check_no is '对账单号'@\
comment on column EBALANCE_RECON_BILL_DESYEAR.child_pack_num is '子包编码'@\
comment on column EBALANCE_RECON_BILL_DESYEAR.current_pack_no is '当前包号'@\
comment on column EBALANCE_RECON_BILL_DESYEAR.pb_code is '代理银行编码'@\
comment on column EBALANCE_RECON_BILL_DESYEAR.pb_name is '代理银行名称'@\
comment on column EBALANCE_RECON_BILL_DESYEAR.begin_date is '对账开始时间'@\
comment on column EBALANCE_RECON_BILL_DESYEAR.end_date is '对账结束时间'@\
comment on column EBALANCE_RECON_BILL_DESYEAR.all_num is '明细总数'@\
comment on column EBALANCE_RECON_BILL_DESYEAR.all_amt is '总金额'@\
comment on column EBALANCE_RECON_BILL_DESYEAR.status is '对账状态'@\
comment on column EBALANCE_RECON_BILL_DESYEAR.xcheckresult is '对账结果'@\
comment on column EBALANCE_RECON_BILL_DESYEAR.xdiffnum is '不符笔数'@\
comment on column EBALANCE_RECON_BILL_DESYEAR.cb_code is '清算行编码'@\
comment on column EBALANCE_RECON_BILL_DESYEAR.cb_name is '清算航名称'@\
comment on column EBALANCE_RECON_BILL_DESYEAR.clear_account_no is '清算行账号'@\
comment on column EBALANCE_RECON_BILL_DESYEAR.clear_account_name is '清算行名称'@\
comment on column EBALANCE_RECON_BILL_DESYEAR.en_code is '预算单位编码'@\
comment on column EBALANCE_RECON_BILL_DESYEAR.en_name is '预算单位名称'@\
comment on column EBALANCE_RECON_BILL_DESYEAR.id is '主单号'@\
comment on column EBALANCE_RECON_BILL_DESYEAR.receive_count is '接收总数'@\
comment on column EBALANCE_RECON_BILL_DESYEAR.latest_op_date is '最后操作日期'@\
comment on column EBALANCE_RECON_BILL_DESYEAR.latest_op_user is '最后操作人'@\
comment on column EBALANCE_RECON_BILL_DESYEAR.create_user is '创建人'@\
comment on column EBALANCE_RECON_BILL_DESYEAR.is_valid is '是否可用'@\
comment on column EBALANCE_RECON_BILL_DESYEAR.mk_code is '资金性质'@\
comment on column EBALANCE_RECON_BILL_DESYEAR.mk_name is '资金性质'@\
comment on column EBALANCE_RECON_BILL_DESYEAR.pk_code is '支出类型'@\
comment on column EBALANCE_RECON_BILL_DESYEAR.pk_name is '支出类型'@\
comment on column EBALANCE_RECON_BILL_DESYEAR.sum_amt is '累计授权支付金额（2514、8514对账主单多出一个金额合计字段“SumAmt累计授权支付金额”）'
SQL_CREATE_COMMENT_EBALANCE_RECON_DETAIL = comment on column EBALANCE_RECON_DETAIL_DESYEAR.voucher_no is '凭证单号'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.detail_id is '对账数据的明细id'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.mk_code is '资金性质编码'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.mk_name is '资金性质名称'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.bo_code is '核算类型'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.bo_name is '核算类型'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.en_code1 is '预算单位'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.en_name1 is '预算单位'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.en_code is '预算单位'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.en_name is '预算单位'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.bs_code is '功能分类'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.bs_name is '功能分类'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.bi_code is '项目分类'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.bi_name is '项目分类'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.pay_account_no is '付款人账号'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.pay_account_name is '付款人名称'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.pay_account_bank is '付款人银行'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.set_month is '月份'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.mb_code is '业务处（科）室'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.mb_name is '业务处（科）室'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.bk_code is '支出类型'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.bk_name is '支出类型'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.bsi_code is '经济分类'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.bsi_name is '经济分类'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.bis_code is '预算项目'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.bis_name is '预算项目'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.pk_code is '支付方式'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.pk_name is '支付方式'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.payee_account_no is '收款人账号'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.payee_account_name is '收款人名称'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.payee_account_bank is '收款人银行'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.pm_code is '结算类型'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.pm_name is '结算类型'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.curdirpayamt is '本期直接支付金额'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.curdirbackamt is '本期直接支付退款金额'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.curdirpayamtsum is '累计直接支付金额'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.curdirbackamtsum is '累计直接支付退款金额'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.curauthplanamt is '本期下达额度金额'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.curauthpayamt is '本期授权支付金额'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.curauthbackamt is '本期授权支付退款金额'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.curauthplanamtsum is '累计下达额度金额'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.curauthpayamtsum is '累计授权支付金额'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.curauthbackamtsum is '累计授权支付退款金额'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.remainplanamt is '授权额度结余金额'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.xcheckresult is '对账结果'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.xcheckreason is '不符原因'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.current_pack_no is '当前包号'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.payagentbillno is '划款单号'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.pb_code is '代理银行编码'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.pb_name is '代理银行名称'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.voucher_check_no is '对账单号'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.xresult_voucher_no is '回单凭证号'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.xcurrent_pack_no is '回单包号'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.predatemoney is '上期额度余额'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.curreckmoney is '本期已清算额度'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.curdatemoney is '本期额度余额'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.pay_voucher_no is '支付凭证号'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.cb_code is '清算行编码'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.cb_name is '清算行名称'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.curpayamt is '本期金额'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.sumpayamt is '累计金额'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.taxorgcode is '税务征收机关代码'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.taxorgname is '征收机关名称'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.budgetlevelcode is '预算级次'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.budgetsubjectcode is '收入分类科目编码'@\
comment on column EBALANCE_RECON_DETAIL_DESYEAR.budgetsubjectname is '收入分类科目名称'